// Include Telegram UI styles first to allow our code override the package CSS.
import React, { useEffect, useRef, useState } from 'react';
import { TonConnectButton, useTonConnectUI } from '@tonconnect/ui-react';

const OWNER_WALLET = 'UQDU0jzNSVGwoTKifH4z4x5BU1zBTl5u8r2JM7mKvnu-ktrC';
const PRICE = 50000000n; // 0.05 TON en nanoton
const RAKE_PERCENT = 15n;

export default function App() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
    const [tonConnectUI] = useTonConnectUI();
      const [score, setScore] = useState(0);
        const [ranking, setRanking] = useState<string>('Cargando ranking...');

          // Cargar ranking
            useEffect(() => {
                fetch('https://sats-eclipse-leaderboard.vercel.app/api/ranking')
                      .then(r => r.json())
                            .then(data => setRanking(data.top10.map((p: any, i: number) => 
                                    `${i+1}. ${p.username} → ${p.score} sats`).join('\n')))
                                          .catch(() => setRanking('Sin conexión'));
                                            }, []);

                                              // Pago + inicio juego
                                                const startGame = async () => {
                                                    if (!tonConnectUI.connected) {
                                                          alert('Conecta tu wallet primero');
                                                                return;
                                                                    }

                                                                        const tx = {
                                                                              validUntil: Math.floor(Date.now() / 1000) + 300,
                                                                                    messages: [{
                                                                                            address: OWNER_WALLET,
                                                                                                    amount: PRICE.toString(),
                                                                                                            payload: btoa('SatsEclipseRunner')
                                                                                                                  }]
                                                                                                                      };

                                                                                                                          try {
                                                                                                                                await tonConnectUI.sendTransaction(tx);
                                                                                                                                      // 15% rake ya llegó a tu wallet
                                                                                                                                            loadPhaserGame();
                                                                                                                                                } catch (e) {
                                                                                                                                                      alert('Pago cancelado');
                                                                                                                                                          }
                                                                                                                                                            };

                                                                                                                                                              const loadPhaserGame = () => {
                                                                                                                                                                  const script = document.createElement('script');
                                                                                                                                                                      script.src = 'https://cdn.jsdelivr.net/npm/phaser@3.80.1/dist/phaser.min.js';
                                                                                                                                                                          script.onload = () => {
                                                                                                                                                                                const Phaser = (window as any).Phaser;
                                                                                                                                                                                      // ← Aquí va todo el juego que ya tenías (mismo código de antes)
                                                                                                                                                                                            // Lo dejo resumido para que quepa, pero es idéntico al que ya probaste
                                                                                                                                                                                                  new Phaser.Game({
                                                                                                                                                                                                          type: Phaser.AUTO,
                                                                                                                                                                                                                  width: 400,
                                                                                                                                                                                                                          height: 600,
                                                                                                                                                                                                                                  parent: canvasRef.current,
                                                                                                                                                                                                                                          backgroundColor: '#000428',
                                                                                                                                                                                                                                                  physics: { default: 'arcade', arcade: { gravity: { y: 800 } } },
                                                                                                                                                                                                                                                          scene: {
                                                                                                                                                                                                                                                                    preload() {
                                                                                                                                                                                                                                                                                this.load.image('plat', 'https://labs.phaser.io/assets/sprites/platform.png');
                                                                                                                                                                                                                                                                                            this.load.spritesheet('player', 'https://labs.phaser.io/assets/sprites/dude.png', 
                                                                                                                                                                                                                                                                                                          { frameWidth: 32, frameHeight: 48 });
                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                              create() {
                                                                                                                                                                                                                                                                                                                                          this.add.text(20, 20, 'Sats Eclipse Runner', { fontSize: '28px', color: '#00ffcc' });
                                                                                                                                                                                                                                                                                                                                                      const platforms = this.physics.add.staticGroup();
                                                                                                                                                                                                                                                                                                                                                                  for (let i = 0; i < 12; i++) {
                                                                                                                                                                                                                                                                                                                                                                                platforms.create(200 + Math.random()*200-100, 550-i*52, 'plat')
                                                                                                                                                                                                                                                                                                                                                                                                .setScale(0.7).refreshBody();
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                        const player = this.physics.add.sprite(200, 100, 'player').setBounce(0.2);
                                                                                                                                                                                                                                                                                                                                                                                                                                    this.physics.add.collider(player, platforms);

                                                                                                                                                                                                                                                                                                                                                                                                                                                let seconds = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.time.addEvent({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          delay: 1000, loop: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        callback: () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        seconds++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (seconds % 30 === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const eclipse = canvasRef.current!.style.filter === 'brightness(0.2)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            canvasRef.current!.style.filter = eclipse ? 'brightness(1)' : 'brightness(0.2)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setScore(s => s + 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.input.on('pointerdown', () => player.setVelocityY(-520));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.body.appendChild(script);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ textAlign: 'center', background: 'linear-gradient(#000428, #004e92)', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              minHeight: '100vh', padding: '20px', color: 'white' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1 style={{ color: '#00ffcc' }}>Sats Eclipse Runner</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TonConnectButton style={{ margin: '20px auto' }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={startGame} style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: '#00ffcc', color: 'black', fontSize: '24px', padding: '15px 30px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: 'none', borderRadius: '15px', margin: '20px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    JUGAR – 0.05 TON
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ color: '#ffff00', fontSize: '22px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Tus sats: {score}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <canvas ref={canvasRef} style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: '5px solid #00ffcc', borderRadius: '16px', marginTop: '10px' 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <pre style={{ background: '#0004', padding: '15px', borderRadius: '10px', marginTop: '20px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {ranking}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }