// Include Telegram UI styles first to allow our code override the package CSS.
import React, { useEffect, useRef } from 'react';

export default function App() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

    useEffect(() => {
        if (!canvasRef.current) return;

            const script = document.createElement('script');
                script.src = 'https://cdn.jsdelivr.net/npm/phaser@3.80.1/dist/phaser.min.js';
                    script.async = true;
                        script.onload = () => {
                              const Phaser = (window as any).Phaser;

                                    new Phaser.Game({
                                            type: Phaser.AUTO,
                                                    width: 400,
                                                            height: 600,
                                                                    parent: canvasRef.current,
                                                                            backgroundColor: '#000428',
                                                                                    physics: { default: 'arcade', arcade: { gravity: { y: 800 }, debug: false } },
                                                                                            scene: {
                                                                                                      preload() {
                                                                                                                  this.load.image('plat', 'https://labs.phaser.io/assets/sprites/platform.png');
                                                                                                                              this.load.image('star', 'https://labs.phaser.io/assets/sprites/star.png');
                                                                                                                                          this.load.spritesheet('player', 'https://labs.phaser.io/assets/sprites/dude.png', { frameWidth: 32, frameHeight: 48 });
                                                                                                                                                    },
                                                                                                                                                              create() {
                                                                                                                                                                          this.add.text(20, 15, 'Sats Eclipse Runner', { fontSize: '26px', color: '#00ffcc' }); login 

                                                                                                                                                                                      const platforms = this.physics.add.staticGroup();
                                                                                                                                                                                                  for (let i = 0; i < 12; i++) {
                                                                                                                                                                                                                platforms.create(200 + Math.random() * 200 - 100, 550 - i * 52, 'plat').setScale(0.7).refreshBody();
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                        const player = this.physics.add.sprite(200, 100, 'player').setBounce(0.2);
                                                                                                                                                                                                                                                    this.physics.add.collider(player, platforms);

                                                                                                                                                                                                                                                                let score = 0;
                                                                                                                                                                                                                                                                            const scoreText = this.add.text(20, 60, 'Sats: 0', { fontSize: '32px', color: '#00ffcc' });

                                                                                                                                                                                                                                                                                        let eclipse = false;
                                                                                                                                                                                                                                                                                                    let seconds = 0;
                                                                                                                                                                                                                                                                                                                this.time.addEvent({
                                                                                                                                                                                                                                                                                                                              delay: 1000,
                                                                                                                                                                                                                                                                                                                                            loop: true,
                                                                                                                                                                                                                                                                                                                                                          callback: () => {
                                                                                                                                                                                                                                                                                                                                                                          seconds++;
                                                                                                                                                                                                                                                                                                                                                                                          if (seconds % 30 === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                            eclipse = !eclipse;
                                                                                                                                                                                                                                                                                                                                                                                                                              canvasRef.current!.style.filter = eclipse ? 'brightness(0.2)' : 'brightness(1)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                score += 1000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  scoreText.setText('Sats: ' + score);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.input.on('pointerdown', () => player.setVelocityY(-520));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.body.appendChild(script);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ textAlign: 'center', background: 'linear-gradient(#000428, #004e92)', minHeight: '100vh', paddingTop: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h1 style={{ color: '#00ffcc', margin: 0 }}>Sats Eclipse Runner</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <canvas ref={canvasRef} style={{ border: '5px solid #00ffcc', borderRadius: '16px', marginTop: '10px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ color: '#ffff00', fontSize: '18px', marginTop: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Tap para saltar • Eclipse cada 30s = +1000 sats
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }